def draw(n):
    if n == 7:
        print("--------")
        print("|       |")
        print("|    ")
        print("|    ")
        print("|    ")
        print("|       ")
        print("|       ")
        print("|       ")
        print("|        ")
        print("|")
        print("-------------")

    elif n == 6:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|       ")
        print("|       ")
        print("|       ")
        print("|        ")
        print("|")
        print("-------------")

    elif n == 5:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|       |")
        print("|       |")
        print("|       ")
        print("|        ")
        print("|")
        print("-------------")

    elif n == 4:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|   ----|")
        print("|       |")
        print("|       ")
        print("|        ")
        print("|")
        print("-------------")

    elif n == 3:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|   ----|----")
        print("|       |")
        print("|       ")
        print("|        ")
        print("|")
        print("-------------")

    elif n == 2:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|   ----|----")
        print("|       |")
        print("|      / ")
        print("|     /   ")
        print("|")
        print("-------------")

    elif n == 1:
        print("--------")
        print("|       |")
        print("|    --------")
        print("|    | .  . |")
        print("|    | /--\ |")
        print("|    --------")
        print("|   ----|----")
        print("|       |")
        print("|      / \ ")
        print("|     /   \ ")
        print("|")
        print("-------------")

    else:
        print("!!  DEAD  !!")
        print("\      /")
        print(" \    /")
        print("  \  /")
        print("   \/")
        print("   /\ ")
        print("  /  \ ")
        print(" /    \ ")
        print("/      \ ")
